default[:xdebug][:remote_enable]    =  ""
default[:xdebug][:remote_handler]   =  ""
default[:xdebug][:remote_mode]      =  ""
default[:xdebug][:remote_host]      =  ""
default[:xdebug][:remote_port]      =  ""